name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Run revive"
        uses: docker://morphy/revive-action:v1

  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: "Run tests"
        run: |
          go get -v -t -d ./...
          go get github.com/haya14busa/goverage
          goverage -race -v -covermode=atomic -coverprofile=coverage.out ./...
        env:
          HITBTC_PUBLIC_KEY: ${{ secrets.HITBTC_PUBLIC_KEY }}
          HITBTC_SECRET_KEY: ${{ secrets.HITBTC_SECRET_KEY }}

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Send coverage"
        run: |
          go get github.com/schrej/godacov
          godacov -t "$CODACY_TOKEN" -r ./coverage.out -c "$COMMIT_SHA"
        env:
          COMMIT_SHA: ${{ github.sha }}
          CODACY_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
